services:
  db:
    image: postgres:16
    container_name: fisio_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fisio
      POSTGRES_USER: fisio
      POSTGRES_PASSWORD: fisio
    ports:
      - "5433:5432"
    volumes:
      - fisio_pgdata:/var/lib/postgresql/data

volumes:
  fisio_pgdata:
